### ISSUE TITLE
[v4.2.0] Changed colors do not appear in mobile devices

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1026]
Changes to main colors do not apply at all to devices with medium to small screens (tablets and smartphones) when using Bootstrap theme. I have't tested with neutron.

This site has a different header color, but only appears in desktop or laptop.

![Screenshot](https://community.phpfox.com/file/attachment/2016/01/0078e8251f302ab0717b3ea1e1b8824e.png)

**Comment by neil96** [comment]
Fixed in V4.2.1.
After upgrade to V4.2.1, you need to revert theme.
If you revert theme you will lose all change. You can backup this file /PF.Site/flavors/bootstrap/assets/variables.less before revert and restore it when done.

**Comment by PhpFoxJohnJr** [comment]
I did revert theme and you are right it does erase all changes (lucky) I wrote them down.  But, check mobile device as well as used your little icons for mobile and tablet (pretty cool) in theme and it still shows original blue color and not the dark color I picked.  I did clear the cache and turned my cloudfare onto development to not cache at all.

**Comment by neil96** [comment]
Could you open new issue and describe your issue more details. We very easy to forget closed issue.

**Comment by Spaninet** [comment]
It is fixed in 4.3?

**Comment by neil96** [comment]
It fixed in 4.3!

**Comment by Spaninet** [comment]
Good!
