### ISSUE TITLE
session request Issues in last version 4.2 b18   

### ISSUE THREAD

**Issue by rn2020** [moxi9/phpfox#1059]
in v4.2rc and older vrstion  he sesion request it was working  but 4.2 stable not work
as i am useing in my secript same login for user in phpfox so they dont need to login again just they go to another folder in the site that script is setup and they dont need to login to the script as i use same info for user in phpfox , it was working great and no problem than ,after the update  it not work
than i try to install the devlop verstion with 4.2rc and test it than it work than if i update to 4.2 b18 it will not work

thread
https://community.phpfox.com/forum/thread/53987/big-issues-in-session-for-phpfox-v4-2-last-version/

Pleas solve it fast in the updated 4.2.1,

**Comment by rn2020** [comment]
have you solve it in 4.2.1

**Comment by rn2020** [comment]
issues is still in the verstion 4.2.1, could we get fast updated for solve it as realy our works is stoping pleas

**Comment by Data66PF** [comment]
Please wait for feedback from one of our testers when they get to this bug. Adding extra comments will make it take longer for testing as they have to read through all the comments first. Thank you.

**Comment by rn2020** [comment]
Hi Donna 
after 6 hours of search from where the issues i found it , 

i will tell you where is the issues of the filed session user get data 

i had install the verstion 4.2rc and i had copy the file 
PF.Base/file/cache/plugin/plugin/data/init.php
to the version 4.2.1 build 5 

and also i copy the file PF.Base/include/init.inc.php  
from verstion 4.2rc to 4.2.1 build 5 


than my script is back to work ok and not   face any login issues and get the user data right 

but if cleared the catch the issues back again 
as the file PF.Base/file/cache/plugin/plugin/data/init.php  back to 4.2.1  build 5 file 

so now the issues is from init.inc.php  and PF.Base/file/cache/plugin/plugin/data/init.php  

i hop i had help you to solve the issues fast , 

if you will take time to solve  it in new update , than pleas tell me from where i can not let the file PF.Base/file/cache/plugin/plugin/data/init.php   not delete auto if i made clear catch

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/issues/1186 is this issue the same as that one? If so, yes it is fixed in 4.3 and you can close this ticket. If not, please let us know.

**Comment by rn2020** [comment]
issues #1186 is delet some info so i could not know what is the full info
about issues as it show the issues for the app  api ...i will test from my
side and replay to you

**Comment by rn2020** [comment]
i think i should see 4.3 if it solve than it is ok if not than it should be
solve so dont close the ticket yet ,,,as my isues in the init.php    and
may you right it is about API ... but let us see as i  back to  the
verstion 4.2 irc   to make it work as  4.2.2 not work ,,, ok i hop it solve

**Comment by Data66PF** [comment]
is this resolved in v4.3?

**Comment by rn2020** [comment]
No it not solved

**Comment by Data66PF** [comment]
@neil96 can you check sometime soon please? or perhaps assign to someone else that can?

**Comment by neil96** [comment]
I can't reproduce this issue on V4.3.1. Could you test again or give me more information. Thanks!

**Comment by rn2020** [comment]
i test and the issues is still there , could you seend me your privet email
to send to you my site to see it by your self

**Comment by neil96** [comment]
Please submit a new ticket here: https://clients.phpfox.com/

**Comment by Data66PF** [comment]
As the bug tracker is for core bugs, we cannot handle this here at this time. We will have a developer forum area open at some time soon though.
