### ISSUE TITLE
Bootstrap Theme | selecting page registration method (group) breaks the page

### ISSUE THREAD

**Issue by optiroot** [moxi9/phpfox#800]
If you have a page that is a group, when you select the page registration method to "Invite only" or "requires approvation", when an user does a request to join the group, the administrator receives the notification but clicking shows a page that merges members of the group and people pending approval all together.

There appears the bar at the bottom of the page to select and approve/disapprove members (as when you approve/disapprove photos) but you can't click any user and there isn't any checkbox to select the user to approve (even because the pending approval, as said, are mixed with the people that is already members). If you click on any user profile you get redirected to their profile.

The link of this page is:
http://website.com/page/1/pending
Or if you have a nice url in the page:
http://website.com/page-nice-url/pending

When the administrator receives the notification "{user} has requested to join the group..." and clicks it, gets redirected to the link above.

I seen that there is an HTML element that should appear on the page's photo cover and indicates the "pending approval" users at the moment, and clicking it will take to the urls above, but this element is "display: none" in PHPfox CSS stylesheet. Making it via Chrome Dev Console "display: block" shows this:
![image](https://cloud.githubusercontent.com/assets/12573563/11709738/5b019932-9f1a-11e5-86e9-dd9186a9df56.png)

(String is translated because the phrase was in "language" packages);
Normally this doesn't appears.
The element is, in three:
```
<div class="breadcrumbs_menu">
  <ul>
    <li>
      <a href="http://website.com/pages/4/pending">Membership in attesa<span class="pending">&nbsp;(1)</span>	</a>
   </li>
  </ul>
</div>
```

This element appears only if there is at least one membership request.

Anyway, I guess that developers were aware of this bug so right for that they made 'hidden' this element. But please if it isn't easy to fix for now at least remove (for now) the option because if an user has a group and sets this, everything gets screwed up...

This happens on v4.1.1 (as I know).

Thank you.

**Comment by Data66PF** [comment]
I'll confirm this for Neutron in mobile we can't see the pending. In Bootstrap on both mobile and desktop, I can't find the pending at all.

**Comment by optiroot** [comment]
Thank you Data, but that's now the only problem: if you go on website.com/pages/4/pending you reach the pending page, but with Bootstrap theme everything is screwed up and you can't choose to approve members or not, even because actual members and who asks to join are mixed.

**Comment by Data66PF** [comment]
Yes but we need to fix both issues as clients need to see the pending showing up where it should since redirection isn't working to end up on the pending area. In Neutron, pending shows on the page itself and should do the same in bootstrap. 
![groupinviteonly scripttechs test site](https://cloud.githubusercontent.com/assets/6908282/11719804/6a7dffb2-9f2a-11e5-8cab-6379ac24b643.png)
![groupinviteonly bootstrap scripttechs test site](https://cloud.githubusercontent.com/assets/6908282/11719807/6d2425a2-9f2a-11e5-8f25-b9e4fb254ef4.png)

**Comment by Data66PF** [comment]
Debug enabled with Bootstrap only, as this error does not show for neutron theme, I get for the direct url to view pending memberships (example http://mysite.com/pages/7/pending)

error:
``` Fatal error: Uncaught exception 'Whoops\Exception\ErrorException' with message 'Undefined index: module' in /home/mysite/web/mysite/public_html/mysite/PF.Base/file/cache/template/core_template_bootstrap_block_template-breadcrumbmenu.html.php.php:26 Stack trace: #0 /home/mysite/web/mysite/public_html/mysite/PF.Base/file/cache/template/core_template_bootstrap_block_template-breadcrumbmenu.html.php.php(26): Whoops\Run->handleError(8, 'Undefined index...', '/home/scripttec...', 26, Array) #1 /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php(3254): require('/home/scripttec...') #2 /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php(3240): Phpfox_Template->_requireFile('/home/scripttec...') #3 /home/mysite/web/mysite/public_html/mysite/PF.Base/include/library/phpfox/template/template.class.php(2529): Phpfox_Template->_getFromCache('/home/scripttec...', 'core.block.temp...') #4 /home/scrip in /home/mysite/web/mysite/public_html/mysite/PF.Src/Core/View/Functions.php on line 184
```

**Comment by neil96** [comment]
Fixed on V4.1.2

**Comment by optiroot** [comment]
This is still not fixed.
First, button doesn't show up

Second, if you select "require approvation" or "invite only", the problem persists. 

Notification arrives to group admin, but when he clicks the notification he gets just redirected to the page.
If you add `/pending` after the page name, you will get the same problem I said in the first post. 
v4.1.2

I can't say about 4.2.0 RC because I have a live site and an active community so I can't test it there.

Data, can you check in 4.2.0? Thank you!

**Comment by Data66PF** [comment]
Please test at our staging site https://stage.phpfox.com and open a new bug if you can reproduce it. thanks.

**Comment by optiroot** [comment]
@Data66PF Tested and the problem still exist...
Attachment:
![image](https://cloud.githubusercontent.com/assets/12573563/12616062/76e84f6e-c509-11e5-8721-864497adde1f.png)

As you can see there is the profile "test1" and the address is https://stage.phpfox.com/pages/28/pending

I don't have any way to accept that member to join my group and if I open the notification it simply brings me to the page https://stage.phpfox.com/pages/28
And that's all...

I don't have any way to accept that member to join my group.

---

In my community is really important this feature; please let me know if this can be fixed in the stable 4.2.1, thank you!
